apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "aksga17-7285"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "aksga17-7285"
    spec:
      containers:
        - name: "aksga17-7285"
          image: "sgacreg.azurecr.io/aksga17"
          ports:
          - containerPort: 8080