apiVersion: v1
kind: Service
metadata:
    name: "aksga17-7285"
    labels:
        app: "aksga17-7285"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "aksga17-7285"